# Generated by Django 4.1.1 on 2022-11-05 21:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('a', 'آذرخش'), ('b', 'بنلی'), ('c', 'آپاچی'), ('d', 'پولسار'), ('e', 'سوزوکی'), ('f', 'هوندا')], max_length=55, verbose_name='برند')),
                ('description', models.TextField(verbose_name='درباره')),
                ('image', models.ImageField(null=True, upload_to='advert photo', verbose_name='تصویر')),
                ('use', models.CharField(choices=[('a', 'همه'), ('b', 'کارکرده'), ('c', 'صقر کیلومتر')], max_length=10, verbose_name='مصرف')),
                ('function', models.IntegerField(default=0, verbose_name='استفاده')),
                ('volume', models.IntegerField(verbose_name='حجم')),
                ('insurance', models.CharField(choices=[('a', 'دارد'), ('b', 'ندارد')], max_length=10, verbose_name='بیمه')),
                ('gearbox', models.CharField(choices=[('a', 'اتوماتیک'), ('b', 'دنده ای')], max_length=10, verbose_name='گیربکس')),
                ('year', models.CharField(choices=[('1370', '۱۳۷۰'), ('1371', '۱۳۷۱'), ('1372', '۱۳۷۲'), ('1373', '۱۳۷۳'), ('1374', '۱۳۷۴'), ('1375', '۱۳۷۵'), ('1376', '۱۳۷۶'), ('1377', '۱۳۷۷'), ('1378', '۱۳۷۸'), ('1379', '۱۳۷۹'), ('1380', '۱۳۸۰'), ('1381', '۱۳۸۱'), ('1382', '۱۳۸۲'), ('1383', '۱۳۸۳'), ('1384', '۱۳۸۴'), ('1385', '۱۳۸۵'), ('1386', '۱۳۸۶'), ('1387', '۱۳۸۷'), ('1388', '۱۳۸۸'), ('1389', '۱۳۸۹'), ('1390', '۱۳۹۰'), ('1391', '۱۳۹۱'), ('1392', '۱۳۹۲'), ('1393', '۱۳۹۳'), ('1394', '۱۳۹۴'), ('1395', '۱۳۹۵'), ('1396', '۱۳۹۶'), ('1397', '۱۳۹۷'), ('1398', '۱۳۹۸'), ('1399', '۱۳۹۹'), ('1400', '۱۴۰۰'), ('1401', '۱۴۰۱')], max_length=5, verbose_name='سال تولید')),
                ('phoneNumber', models.CharField(default='0', max_length=11, verbose_name='شماره تلفن')),
                ('color', models.CharField(choices=[('a', 'نقره ای'), ('b', 'زرشکی'), ('c', 'مارون'), ('d', 'نوک مدادی'), ('e', 'نارنجی'), ('f', 'بژ'), ('g', 'مشکی'), ('h', 'سفید'), ('i', 'قهوه ای'), ('j', 'قرمز'), ('k', 'آبی')], max_length=10, verbose_name='رنگ')),
                ('fuel', models.CharField(choices=[('a', 'بنزینی'), ('b', 'گازی'), ('c', 'گازویل')], max_length=10, verbose_name='مصرف')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='زمان ایجاد')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی ها',
            },
        ),
    ]
